freebsd_instance:
  image_family: freebsd-13-0-snap # 13.0 boots way faster

task:
  matrix:
    - name: cargo test (nightly)
      env:
        VERSION: +nightly-2019-09-26-x86_64-unknown-freebsd
    - name: cargo test (stable)
      env:
        VERSION: +1.38.0
  setup_script:
    - pkg install -y c-blosc isa-l fusefs-libs pkgconf
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
    - $HOME/.cargo/bin/rustup toolchain install 1.38.0
    # A bug appeared in nightly-2019-09-28 that causes the build to fail with
    # an internal compiler error.  Probably related to
    # https://github.com/rust-lang/rust/issues/54114
    - $HOME/.cargo/bin/rustup toolchain install nightly-2019-09-26-x86_64-unknown-freebsd
    # In 11.3, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script:
      - echo $VERSION
      - cat Cargo.lock || echo ""
  target_cache:
    folder: target
    fingerprint_script: echo $VERSION
  build_script:
    - . $HOME/.cargo/env
    - cargo $VERSION build --all-features --all
  test_script:
    - . $HOME/.cargo/env
    - cargo $VERSION test --all-features --all --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
