freebsd_instance:
  image: freebsd-11-3-stable-amd64-v20190801

task:
  env:
    HOME: /tmp # cargo needs it
  matrix:
    - name: cargo test (nightly)
      env:
        VERSION: +nightly
        CARGO_ARGS: --all-features
    - name: cargo test (stable)
      env:
        VERSION: +1.39.0
  setup_script:
    - pkg install -y c-blosc isa-l fusefs-libs pkgconf
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
    - $HOME/.cargo/bin/rustup toolchain install 1.39.0
    - $HOME/.cargo/bin/rustup toolchain install nightly
    # In 11.3, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo $VERSION build $CARGO_ARGS --all
  test_script:
    - . $HOME/.cargo/env
    - cargo $VERSION test $CARGO_ARGS --all --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
