[package]
name = "bfffs"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[lib]
# BFFFS doesn't use doctests, because it's not a real library.
doctest = false

[features]
nightly = []

[dependencies]
bincode = { version = "1.0.1", features = ["i128"] }
bitfield = "0.13.1"
blosc = { git = "https://github.com/asomers/blosc-rs/", rev = "04c9e02"}
byteorder = "1.2.3"
cfg-if = "0.1"
divbuf = { git = "https://github.com/asomers/divbuf.git", rev = "0a72fb5"}
downcast = "0.10.0"
enum-primitive-derive = "^0.1"
fixedbitset = "0.1.8"
futures = "0.1.14"
futures-locks = "0.5"
itertools = "0.7"
isa-l = { path = "../isa-l" }
lazy_static = "1.0"
libc = "0.2.44"
metrohash = "1.0"
nix = "0.15.0"
num-traits = "^0.1"
serde = "1.0.60"
serde_derive = "1.0"
serde_yaml = "0.8.6"
time = "0.1"
tokio = "0.1.8"
tokio-current-thread = "0.1.1"
tokio-file = "0.5.1"
tokio-io-pool = "0.1.4"
uuid = { version = "0.7", features = ["serde", "v4"]}

[dependencies.clap]
version = "2"
default-features = false
features=  [ "suggestions", "color", "wrap_help" ]

[dev-dependencies]
chashmap = "2"
env_logger = "0.5"
galvanic-test = "0.2"
glob = "0.2"
histogram = "0.6"
itertools = "0.7.1"
log = "0.4"
mockall = "0.5.2"
num_cpus = "1"
permutohedron = "0.2"
pretty_assertions = "0.5"
rand = "0.6"
rand_xorshift = "0.1"
tempdir = "0.3"
