name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - freebsd_version: "15.0"
          rust_version: "nightly"
          target: x86_64-unknown-freebsd
          arch: x86_64
        - freebsd_version: "14.4"
          rust_version: "1.85.0"
          target: x86_64-unknown-freebsd
          arch: x86_64
        - freebsd_version: "14.4"
          rust_version: "1.85.0"
          target: i686-unknown-freebsd
          arch: i686
    name: FreeBSD/${{ matrix.arch }} ${{ matrix.freebsd_version }} ${{ matrix.rust_version }}
    steps:
    - uses: actions/checkout@v6
    - name: Start VM
      uses: vmactions/freebsd-vm@v1
      with:
        release: ${{ matrix.freebsd_version }}
        usesh: true
    - name: Install dependencies
      shell: freebsd {0}
      run: |
        pkg install -y curl
        fetch https://sh.rustup.rs -o rustup.sh
        sh rustup.sh -y --profile=minimal --default-toolchain ${{ matrix.rust_version }}
        . $HOME/.cargo/env
        if [ "${{ matrix.target }}" = "i686-unknown-freebsd" ]; then rustup target add --toolchain ${{ matrix.rust_version }} i686-unknown-freebsd; fi
    - name: Test
      shell: freebsd {0}
      run: |
        . $HOME/.cargo/env
        cargo test --target ${{ matrix.target }}
    - name: Doc
      shell: freebsd {0}
      run: |
        . $HOME/.cargo/env
        cargo doc --target ${{ matrix.target }} --no-deps
    - name: Clippy
      if: matrix.rust_version == 'nightly' 
      shell: freebsd {0}
      run: |
        . $HOME/.cargo/env
        rustup component add --toolchain nightly clippy
        cargo +nightly clippy --all-targets -- -D warnings
    - name: Fmt
      if: matrix.rust_version == 'nightly' 
      shell: freebsd {0}
      run: |
        . $HOME/.cargo/env
        rustup component add --toolchain nightly rustfmt
        cargo +nightly fmt --all -- --check --color=never
    - name: Audit
      if: matrix.rust_version == 'nightly' 
      shell: freebsd {0}
      run: |
        . $HOME/.cargo/env
        pkg install -y cargo-audit
        cargo audit
